### ISSUE TITLE
vvass auf dem pi

### ISSUE THREAD

**Issue by yannik-b** [shackspace/vvass#1]
Hallo,
ich versuche gerade das Skript auf einem Raspberry Pi B Rev 2 zum Laufen zu Bringen.
Er findet alle möglichen Module nicht.
Kann mir jemand helfen, die Module richtig zu installieren?

**Comment by c1ko** [comment]
Hi, I recommend you to use https://efa-api.asw.io/api/v1/ - the code is a lot cleaner.
Examples on how to use it can be found in https://github.com/shackspace/kiosk_v4/blob/master/vvs.js
The sourcecode is available @ https://github.com/opendata-stuttgart/metaEFA

**Comment by yannik-b** [comment]
You could add the info "DEPRECATED" with the reason given above to the top of the readme. 
For other people who want to use a json API for the VVS

Best regards
